@host=https://localhost:7290

GET {{host}}/dinners
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZjcwMTFlNC1hNjE4LTRlNzQtYWUxOS1hNGJhNjY4OTBhYmIiLCJnaXZlbl9uYW1lIjoiU2hpcmlrIiwiZmFtaWx5X25hbWUiOiJLcnV0b3kiLCJqdGkiOiJkMmZlMTMxNy05ZjdiLTQyZTgtOTEzNS00YjMyMTZkZWRmM2UiLCJleHAiOjE2OTE5Mzc1NjQsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.D4hfOULkXJxBhVyEZ6RfKhjHe8UAHgxHDlCq509D8j8